<?php

return [
    'allowed_html' => [
        'p[class]',
        'div[class]',
        'span[class]',
        'br',
        'hr',
        'h1[class]',
        'h2[class]',
        'h3[class]',
        'h4[class]',
        'h5[class]',
        'h6[class]',
        'ul[class]',
        'ol[class]',
        'li[class]',
        '*[class]',
        'a[href|target|rel|class|title]',
        'img[src|alt|class]',
        'strong[class]',
        'em[class]',
        'b[class]',
        'i[class]',
        'u[class]',
        'blockquote[class]',
        'pre[class]',
        'code[class]',
        'table[class]',
        'thead[class]',
        'tbody[class]',
        'tr[class]',
        'th[class]',
        'td[class]',
        'figure[class]',
        'figcaption[class]',
        'video[class|controls|poster|preload]',
        'audio[class|controls|preload]',
        'source[src|type]',
        'embed[src|type]',
        'iframe[src|class|allow|allowfullscreen|frameborder|loading|title]',
    ],

    'safe_iframe' => true,
    'safe_iframe_regexp' => '%^(?:https?:)?//(?:www\.|)(?:youtube(?:-nocookie)?\.com|youtu\.be|vimeo\.com|youtube\.com)%',
    'allowed_frameborder' => true,
    'allowed_frame_targets' => ['_blank' => true],
    'allowed_rel' => ['nofollow' => true, 'noopener' => true, 'noreferrer' => true],
    'target_blank' => false,
    'target_noopener' => true,
    'target_noreferrer' => true,

    'css_allowed_properties' => [
        'text-align',
        'color',
        'background-color',
        'font-size',
        'font-weight',
        'margin',
        'padding',
    ],

    'forbidden_elements' => [
        'script',
        'style',
        'object',
        'applet',
        'meta',
        'link',
        'base',
        'basefont',
    ],

    'forbidden_attributes' => [
        'onclick',
        'onerror',
        'onload',
        'onmouseover',
        'onkeydown',
        'onkeyup',
        'onchange',
        'onsubmit',
    ],
];
