-- SevenRockRadio database cleanup by phases
-- Source audit: docs/database-audit.md
-- Recommended order:
--   1) backup
--   2) run phase 1
--   3) validate app
--   4) run phase 2 only if you are sure those plugins/features are not needed
--   5) keep a final backup before any optional drops

START TRANSACTION;

-- ------------------------------------------------------------
-- PHASE 1: staging / clone noise
-- Safe to remove after backup
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `wpstg0_actionscheduler_actions`;
DROP TABLE IF EXISTS `wpstg0_actionscheduler_claims`;
DROP TABLE IF EXISTS `wpstg0_actionscheduler_groups`;
DROP TABLE IF EXISTS `wpstg0_actionscheduler_logs`;
DROP TABLE IF EXISTS `wpstg0_addonlibrary_addons`;
DROP TABLE IF EXISTS `wpstg0_addonlibrary_categories`;
DROP TABLE IF EXISTS `wpstg0_b2s_posts`;
DROP TABLE IF EXISTS `wpstg0_b2s_posts_drafts`;
DROP TABLE IF EXISTS `wpstg0_b2s_posts_favorites`;
DROP TABLE IF EXISTS `wpstg0_b2s_posts_network_details`;
DROP TABLE IF EXISTS `wpstg0_b2s_posts_sched_details`;
DROP TABLE IF EXISTS `wpstg0_b2s_user`;
DROP TABLE IF EXISTS `wpstg0_b2s_user_contact`;
DROP TABLE IF EXISTS `wpstg0_b2s_user_network_settings`;
DROP TABLE IF EXISTS `wpstg0_comments`;
DROP TABLE IF EXISTS `wpstg0_commentmeta`;
DROP TABLE IF EXISTS `wpstg0_fea_emails`;
DROP TABLE IF EXISTS `wpstg0_fea_plans`;
DROP TABLE IF EXISTS `wpstg0_fea_submissions`;
DROP TABLE IF EXISTS `wpstg0_fea_subscriptions`;
DROP TABLE IF EXISTS `wpstg0_hostinger_reach_carts`;
DROP TABLE IF EXISTS `wpstg0_hostinger_reach_contact_lists`;
DROP TABLE IF EXISTS `wpstg0_hostinger_reach_forms`;
DROP TABLE IF EXISTS `wpstg0_l24bd_wpcounter_visitors`;
DROP TABLE IF EXISTS `wpstg0_lbg_audio11_html5_shoutcast_players`;
DROP TABLE IF EXISTS `wpstg0_lbg_audio11_html5_shoutcast_settings`;
DROP TABLE IF EXISTS `wpstg0_links`;
DROP TABLE IF EXISTS `wpstg0_litespeed_url`;
DROP TABLE IF EXISTS `wpstg0_litespeed_url_file`;
DROP TABLE IF EXISTS `wpstg0_masterslider_options`;
DROP TABLE IF EXISTS `wpstg0_masterslider_sliders`;
DROP TABLE IF EXISTS `wpstg0_mlw_qm_audit_trail`;
DROP TABLE IF EXISTS `wpstg0_mlw_questions`;
DROP TABLE IF EXISTS `wpstg0_mlw_quizzes`;
DROP TABLE IF EXISTS `wpstg0_mlw_results`;
DROP TABLE IF EXISTS `wpstg0_nextend2_image_storage`;
DROP TABLE IF EXISTS `wpstg0_nextend2_section_storage`;
DROP TABLE IF EXISTS `wpstg0_nextend2_smartslider3_generators`;
DROP TABLE IF EXISTS `wpstg0_nextend2_smartslider3_sliders`;
DROP TABLE IF EXISTS `wpstg0_nextend2_smartslider3_sliders_xref`;
DROP TABLE IF EXISTS `wpstg0_nextend2_smartslider3_slides`;
DROP TABLE IF EXISTS `wpstg0_options`;
DROP TABLE IF EXISTS `wpstg0_page_visit_history`;
DROP TABLE IF EXISTS `wpstg0_page_visit_referer`;
DROP TABLE IF EXISTS `wpstg0_page_visit_wizard`;
DROP TABLE IF EXISTS `wpstg0_postmeta`;
DROP TABLE IF EXISTS `wpstg0_rank_math_404_logs`;
DROP TABLE IF EXISTS `wpstg0_rank_math_analytics_objects`;
DROP TABLE IF EXISTS `wpstg0_rank_math_internal_links`;
DROP TABLE IF EXISTS `wpstg0_rank_math_internal_meta`;
DROP TABLE IF EXISTS `wpstg0_rank_math_redirections`;
DROP TABLE IF EXISTS `wpstg0_rank_math_redirections_cache`;
DROP TABLE IF EXISTS `wpstg0_smush_dir_images`;
DROP TABLE IF EXISTS `wpstg0_statistics_exclusions`;
DROP TABLE IF EXISTS `wpstg0_statistics_historical`;
DROP TABLE IF EXISTS `wpstg0_statistics_pages`;
DROP TABLE IF EXISTS `wpstg0_statistics_search`;
DROP TABLE IF EXISTS `wpstg0_statistics_useronline`;
DROP TABLE IF EXISTS `wpstg0_statistics_visit`;
DROP TABLE IF EXISTS `wpstg0_statistics_visitor`;
DROP TABLE IF EXISTS `wpstg0_statistics_visitor_relationships`;
DROP TABLE IF EXISTS `wpstg0_term_relationships`;
DROP TABLE IF EXISTS `wpstg0_term_taxonomy`;
DROP TABLE IF EXISTS `wpstg0_termmeta`;
DROP TABLE IF EXISTS `wpstg0_terms`;
DROP TABLE IF EXISTS `wpstg0_useful_banner_manager_banners`;
DROP TABLE IF EXISTS `wpstg0_usermeta`;
DROP TABLE IF EXISTS `wpstg0_users`;
DROP TABLE IF EXISTS `wpstg0_wp_floating_menu_custom_templates`;
DROP TABLE IF EXISTS `wpstg0_wp_floating_menu_details`;
DROP TABLE IF EXISTS `wpstg0_yoast_indexable`;
DROP TABLE IF EXISTS `wpstg0_yoast_indexable_hierarchy`;
DROP TABLE IF EXISTS `wpstg0_yoast_migrations`;
DROP TABLE IF EXISTS `wpstg0_yoast_primary_term`;
DROP TABLE IF EXISTS `wpstg0_yoast_prominent_words`;
DROP TABLE IF EXISTS `wpstg0_yoast_seo_links`;

DROP TABLE IF EXISTS `uibnVeTfblc_filters`;
DROP TABLE IF EXISTS `uibnVeTfblc_instances`;
DROP TABLE IF EXISTS `uibnVeTfblc_links`;
DROP TABLE IF EXISTS `uibnVeTfblc_synch`;
DROP TABLE IF EXISTS `uibnVeTfcommentmeta`;
DROP TABLE IF EXISTS `uibnVeTfcomments`;
DROP TABLE IF EXISTS `uibnVeTfduplicator_pro_entities`;
DROP TABLE IF EXISTS `uibnVeTfduplicator_pro_packages`;
DROP TABLE IF EXISTS `uibnVeTflinks`;
DROP TABLE IF EXISTS `uibnVeTfoptions`;
DROP TABLE IF EXISTS `uibnVeTfpostmeta`;
DROP TABLE IF EXISTS `uibnVeTfposts`;
DROP TABLE IF EXISTS `uibnVeTfrcb_asset_seo_redirect`;
DROP TABLE IF EXISTS `uibnVeTfrcb_blocker_thumbnails`;
DROP TABLE IF EXISTS `uibnVeTfrcb_consent`;
DROP TABLE IF EXISTS `uibnVeTfrcb_presets`;
DROP TABLE IF EXISTS `uibnVeTfrcb_revision`;
DROP TABLE IF EXISTS `uibnVeTfrcb_revision_independent`;
DROP TABLE IF EXISTS `uibnVeTfrcb_scan`;
DROP TABLE IF EXISTS `uibnVeTfrcb_scan_markup`;
DROP TABLE IF EXISTS `uibnVeTfrcb_stats`;
DROP TABLE IF EXISTS `uibnVeTfrcb_tcf_features`;
DROP TABLE IF EXISTS `uibnVeTfrcb_tcf_purposes`;
DROP TABLE IF EXISTS `uibnVeTfrcb_tcf_special_features`;
DROP TABLE IF EXISTS `uibnVeTfrcb_tcf_special_purposes`;
DROP TABLE IF EXISTS `uibnVeTfrcb_tcf_stacks`;
DROP TABLE IF EXISTS `uibnVeTfrcb_tcf_vendors`;
DROP TABLE IF EXISTS `uibnVeTfreal_queue`;
DROP TABLE IF EXISTS `uibnVeTfstatify`;
DROP TABLE IF EXISTS `uibnVeTfterm_relationships`;
DROP TABLE IF EXISTS `uibnVeTfterm_taxonomy`;
DROP TABLE IF EXISTS `uibnVeTftermmeta`;
DROP TABLE IF EXISTS `uibnVeTfterms`;
DROP TABLE IF EXISTS `uibnVeTfusermeta`;
DROP TABLE IF EXISTS `uibnVeTfusers`;

-- ------------------------------------------------------------
-- PHASE 2: plugin tables that are not part of the Laravel app
-- Use only if you no longer need the related plugin/features
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `wpsr_actionscheduler_actions`;
DROP TABLE IF EXISTS `wpsr_actionscheduler_claims`;
DROP TABLE IF EXISTS `wpsr_actionscheduler_groups`;
DROP TABLE IF EXISTS `wpsr_actionscheduler_logs`;
DROP TABLE IF EXISTS `wpsr_aioseo_crawl_cleanup_blocked_args`;
DROP TABLE IF EXISTS `wpsr_aioseo_crawl_cleanup_logs`;
DROP TABLE IF EXISTS `wpsr_aioseo_notifications`;
DROP TABLE IF EXISTS `wpsr_aioseo_posts`;
DROP TABLE IF EXISTS `wpsr_b2s_network_insights`;
DROP TABLE IF EXISTS `wpsr_b2s_posts`;
DROP TABLE IF EXISTS `wpsr_b2s_posts_drafts`;
DROP TABLE IF EXISTS `wpsr_b2s_posts_favorites`;
DROP TABLE IF EXISTS `wpsr_b2s_posts_insights`;
DROP TABLE IF EXISTS `wpsr_b2s_posts_network_details`;
DROP TABLE IF EXISTS `wpsr_b2s_posts_sched_details`;
DROP TABLE IF EXISTS `wpsr_b2s_user`;
DROP TABLE IF EXISTS `wpsr_b2s_user_contact`;
DROP TABLE IF EXISTS `wpsr_b2s_user_network_settings`;
DROP TABLE IF EXISTS `wpsr_cerber_files`;
DROP TABLE IF EXISTS `wpsr_cerber_sets`;
DROP TABLE IF EXISTS `wpsr_cerber_uss`;
DROP TABLE IF EXISTS `wpsr_cerber_acl`;
DROP TABLE IF EXISTS `wpsr_cerber_blocks`;
DROP TABLE IF EXISTS `wpsr_cerber_countries`;
DROP TABLE IF EXISTS `wpsr_cerber_lab`;
DROP TABLE IF EXISTS `wpsr_cerber_lab_ip`;
DROP TABLE IF EXISTS `wpsr_cerber_lab_net`;
DROP TABLE IF EXISTS `wpsr_cerber_log`;
DROP TABLE IF EXISTS `wpsr_cerber_qmem`;
DROP TABLE IF EXISTS `wpsr_cerber_traffic`;
DROP TABLE IF EXISTS `wpsr_commentmeta`;
DROP TABLE IF EXISTS `wpsr_comments`;
DROP TABLE IF EXISTS `wpsr_connections`;
DROP TABLE IF EXISTS `wpsr_connections_address`;
DROP TABLE IF EXISTS `wpsr_connections_date`;
DROP TABLE IF EXISTS `wpsr_connections_email`;
DROP TABLE IF EXISTS `wpsr_connections_link`;
DROP TABLE IF EXISTS `wpsr_connections_messenger`;
DROP TABLE IF EXISTS `wpsr_connections_meta`;
DROP TABLE IF EXISTS `wpsr_connections_phone`;
DROP TABLE IF EXISTS `wpsr_connections_social`;
DROP TABLE IF EXISTS `wpsr_connections_term_meta`;
DROP TABLE IF EXISTS `wpsr_connections_term_relationships`;
DROP TABLE IF EXISTS `wpsr_connections_term_taxonomy`;
DROP TABLE IF EXISTS `wpsr_connections_terms`;
DROP TABLE IF EXISTS `wpsr_ctf_feeds_posts`;
DROP TABLE IF EXISTS `wpsr_ctf_posts`;
DROP TABLE IF EXISTS `wpsr_depicter_documents`;
DROP TABLE IF EXISTS `wpsr_depicter_lead_fields`;
DROP TABLE IF EXISTS `wpsr_depicter_leads`;
DROP TABLE IF EXISTS `wpsr_depicter_meta`;
DROP TABLE IF EXISTS `wpsr_depicter_options`;
DROP TABLE IF EXISTS `wpsr_duplicator_backups`;
DROP TABLE IF EXISTS `wpsr_duplicator_entities`;
DROP TABLE IF EXISTS `wpsr_dzsap_activity`;
DROP TABLE IF EXISTS `wpsr_e_events`;
DROP TABLE IF EXISTS `wpsr_e_notes`;
DROP TABLE IF EXISTS `wpsr_e_notes_users_relations`;
DROP TABLE IF EXISTS `wpsr_e_submissions`;
DROP TABLE IF EXISTS `wpsr_e_submissions_actions_log`;
DROP TABLE IF EXISTS `wpsr_e_submissions_values`;
DROP TABLE IF EXISTS `wpsr_fea_emails`;
DROP TABLE IF EXISTS `wpsr_fea_plans`;
DROP TABLE IF EXISTS `wpsr_fea_submissions`;
DROP TABLE IF EXISTS `wpsr_fea_subscriptions`;
DROP TABLE IF EXISTS `wpsr_hostinger_reach_carts`;
DROP TABLE IF EXISTS `wpsr_hostinger_reach_contact_lists`;
DROP TABLE IF EXISTS `wpsr_hostinger_reach_forms`;
DROP TABLE IF EXISTS `wpsr_jetpack_sync_queue`;
DROP TABLE IF EXISTS `wpsr_jetpack_waf_blocklog`;
DROP TABLE IF EXISTS `wpsr_layerslider`;
DROP TABLE IF EXISTS `wpsr_layerslider_revisions`;
DROP TABLE IF EXISTS `wpsr_lbg_audio11_html5_shoutcast_players`;
DROP TABLE IF EXISTS `wpsr_lbg_audio11_html5_shoutcast_settings`;
DROP TABLE IF EXISTS `wpsr_lbg_audio4_html5_shoutcast_categories`;
DROP TABLE IF EXISTS `wpsr_lbg_audio4_html5_shoutcast_players`;
DROP TABLE IF EXISTS `wpsr_lbg_audio4_html5_shoutcast_playlist`;
DROP TABLE IF EXISTS `wpsr_lbg_audio4_html5_shoutcast_settings`;
DROP TABLE IF EXISTS `wpsr_lbg_audio9_html5_radio_zuper_players`;
DROP TABLE IF EXISTS `wpsr_lbg_audio9_html5_radio_zuper_settings`;
DROP TABLE IF EXISTS `wpsr_links`;
DROP TABLE IF EXISTS `wpsr_litespeed_avatar`;
DROP TABLE IF EXISTS `wpsr_litespeed_img_optming`;
DROP TABLE IF EXISTS `wpsr_litespeed_url`;
DROP TABLE IF EXISTS `wpsr_litespeed_url_file`;
DROP TABLE IF EXISTS `wpsr_mailchimp_carts`;
DROP TABLE IF EXISTS `wpsr_mailchimp_jobs`;
DROP TABLE IF EXISTS `wpsr_masterslider_options`;
DROP TABLE IF EXISTS `wpsr_masterslider_sliders`;
DROP TABLE IF EXISTS `wpsr_mclean_refs`;
DROP TABLE IF EXISTS `wpsr_mclean_scan`;
DROP TABLE IF EXISTS `wpsr_nextend2_image_storage`;
DROP TABLE IF EXISTS `wpsr_nextend2_section_storage`;
DROP TABLE IF EXISTS `wpsr_nextend2_smartslider3_generators`;
DROP TABLE IF EXISTS `wpsr_nextend2_smartslider3_sliders`;
DROP TABLE IF EXISTS `wpsr_nextend2_smartslider3_sliders_xref`;
DROP TABLE IF EXISTS `wpsr_nextend2_smartslider3_slides`;
DROP TABLE IF EXISTS `wpsr_odb_logs`;
DROP TABLE IF EXISTS `wpsr_page_visit_history`;
DROP TABLE IF EXISTS `wpsr_page_visit_referer`;
DROP TABLE IF EXISTS `wpsr_page_visit_wizard`;
DROP TABLE IF EXISTS `wpsr_pmpro_discount_codes`;
DROP TABLE IF EXISTS `wpsr_pmpro_discount_codes_levels`;
DROP TABLE IF EXISTS `wpsr_pmpro_discount_codes_uses`;
DROP TABLE IF EXISTS `wpsr_pmpro_groups`;
DROP TABLE IF EXISTS `wpsr_pmpro_membership_levelmeta`;
DROP TABLE IF EXISTS `wpsr_pmpro_membership_levels`;
DROP TABLE IF EXISTS `wpsr_pmpro_membership_levels_groups`;
DROP TABLE IF EXISTS `wpsr_pmpro_membership_ordermeta`;
DROP TABLE IF EXISTS `wpsr_pmpro_membership_orders`;
DROP TABLE IF EXISTS `wpsr_pmpro_memberships_categories`;
DROP TABLE IF EXISTS `wpsr_pmpro_memberships_pages`;
DROP TABLE IF EXISTS `wpsr_pmpro_memberships_users`;
DROP TABLE IF EXISTS `wpsr_pmpro_subscriptionmeta`;
DROP TABLE IF EXISTS `wpsr_pmpro_subscriptions`;
DROP TABLE IF EXISTS `wpsr_popularpostsdata`;
DROP TABLE IF EXISTS `wpsr_popularpostssummary`;
DROP TABLE IF EXISTS `wpsr_popularpoststransients`;
DROP TABLE IF EXISTS `wpsr_presto_player_email_collection`;
DROP TABLE IF EXISTS `wpsr_pv_commission`;
DROP TABLE IF EXISTS `wpsr_pvc_daily`;
DROP TABLE IF EXISTS `wpsr_pvc_total`;
DROP TABLE IF EXISTS `wpsr_rp4wp_cache`;
DROP TABLE IF EXISTS `wpsr_sms_otp`;
DROP TABLE IF EXISTS `wpsr_sms_otp_attempts`;
DROP TABLE IF EXISTS `wpsr_sms_send`;
DROP TABLE IF EXISTS `wpsr_sms_subscribes`;
DROP TABLE IF EXISTS `wpsr_sms_subscribes_group`;
DROP TABLE IF EXISTS `wpsr_sonaar_events`;
DROP TABLE IF EXISTS `wpsr_term_relationships`;
DROP TABLE IF EXISTS `wpsr_term_taxonomy`;
DROP TABLE IF EXISTS `wpsr_termmeta`;
DROP TABLE IF EXISTS `wpsr_terms`;
DROP TABLE IF EXISTS `wpsr_tm_taskmeta`;
DROP TABLE IF EXISTS `wpsr_tm_tasks`;
DROP TABLE IF EXISTS `wpsr_ulike`;
DROP TABLE IF EXISTS `wpsr_ulike_activities`;
DROP TABLE IF EXISTS `wpsr_ulike_comments`;
DROP TABLE IF EXISTS `wpsr_ulike_forums`;
DROP TABLE IF EXISTS `wpsr_ulike_meta`;
DROP TABLE IF EXISTS `wpsr_userfeedback_survey_responses`;
DROP TABLE IF EXISTS `wpsr_userfeedback_surveys`;
DROP TABLE IF EXISTS `wpsr_wc_admin_note_actions`;
DROP TABLE IF EXISTS `wpsr_wc_admin_notes`;
DROP TABLE IF EXISTS `wpsr_wc_category_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_customer_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_download_log`;
DROP TABLE IF EXISTS `wpsr_wc_order_coupon_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_order_product_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_order_stats`;
DROP TABLE IF EXISTS `wpsr_wc_order_tax_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_product_attributes_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_product_download_directories`;
DROP TABLE IF EXISTS `wpsr_wc_product_meta_lookup`;
DROP TABLE IF EXISTS `wpsr_wc_rate_limits`;
DROP TABLE IF EXISTS `wpsr_wc_reserved_stock`;
DROP TABLE IF EXISTS `wpsr_wc_tax_rate_classes`;
DROP TABLE IF EXISTS `wpsr_wc_webhooks`;
DROP TABLE IF EXISTS `wpsr_wcv_reports_cache`;
DROP TABLE IF EXISTS `wpsr_woocommerce_api_keys`;
DROP TABLE IF EXISTS `wpsr_woocommerce_attribute_taxonomies`;
DROP TABLE IF EXISTS `wpsr_woocommerce_downloadable_product_permissions`;
DROP TABLE IF EXISTS `wpsr_woocommerce_log`;
DROP TABLE IF EXISTS `wpsr_woocommerce_order_itemmeta`;
DROP TABLE IF EXISTS `wpsr_woocommerce_order_items`;
DROP TABLE IF EXISTS `wpsr_woocommerce_payment_tokenmeta`;
DROP TABLE IF EXISTS `wpsr_woocommerce_payment_tokens`;
DROP TABLE IF EXISTS `wpsr_woocommerce_sessions`;
DROP TABLE IF EXISTS `wpsr_woocommerce_shipping_zone_locations`;
DROP TABLE IF EXISTS `wpsr_woocommerce_shipping_zone_methods`;
DROP TABLE IF EXISTS `wpsr_woocommerce_shipping_zones`;
DROP TABLE IF EXISTS `wpsr_woocommerce_tax_rate_locations`;
DROP TABLE IF EXISTS `wpsr_woocommerce_tax_rates`;
DROP TABLE IF EXISTS `wpsr_wpfm_backup`;
DROP TABLE IF EXISTS `wpsr_wpforms_logs`;
DROP TABLE IF EXISTS `wpsr_wpforms_payment_meta`;
DROP TABLE IF EXISTS `wpsr_wpforms_payments`;
DROP TABLE IF EXISTS `wpsr_wpforms_tasks_meta`;
DROP TABLE IF EXISTS `wpsr_yoast_indexable`;
DROP TABLE IF EXISTS `wpsr_yoast_indexable_hierarchy`;
DROP TABLE IF EXISTS `wpsr_yoast_migrations`;
DROP TABLE IF EXISTS `wpsr_yoast_primary_term`;
DROP TABLE IF EXISTS `wpsr_yoast_prominent_words`;
DROP TABLE IF EXISTS `wpsr_yoast_seo_links`;
DROP TABLE IF EXISTS `wpsr_zbs_admlog`;
DROP TABLE IF EXISTS `wpsr_zbs_aka`;
DROP TABLE IF EXISTS `wpsr_zbs_companies`;
DROP TABLE IF EXISTS `wpsr_zbs_contacts`;
DROP TABLE IF EXISTS `wpsr_zbs_customfields`;
DROP TABLE IF EXISTS `wpsr_zbs_dbmigration_meta`;
DROP TABLE IF EXISTS `wpsr_zbs_dbmigration_posts`;
DROP TABLE IF EXISTS `wpsr_zbs_event_reminders`;
DROP TABLE IF EXISTS `wpsr_zbs_events`;
DROP TABLE IF EXISTS `wpsr_zbs_externalsources`;
DROP TABLE IF EXISTS `wpsr_zbs_forms`;
DROP TABLE IF EXISTS `wpsr_zbs_invoices`;
DROP TABLE IF EXISTS `wpsr_zbs_lineitems`;
DROP TABLE IF EXISTS `wpsr_zbs_logs`;
DROP TABLE IF EXISTS `wpsr_zbs_meta`;
DROP TABLE IF EXISTS `wpsr_zbs_notifications`;
DROP TABLE IF EXISTS `wpsr_zbs_object_links`;
DROP TABLE IF EXISTS `wpsr_zbs_quotes`;
DROP TABLE IF EXISTS `wpsr_zbs_quotes_templates`;
DROP TABLE IF EXISTS `wpsr_zbs_security_log`;
DROP TABLE IF EXISTS `wpsr_zbs_segments`;
DROP TABLE IF EXISTS `wpsr_zbs_segments_conditions`;
DROP TABLE IF EXISTS `wpsr_zbs_settings`;
DROP TABLE IF EXISTS `wpsr_zbs_sys_cronmanagerlogs`;
DROP TABLE IF EXISTS `wpsr_zbs_sys_email`;
DROP TABLE IF EXISTS `wpsr_zbs_sys_email_hist`;
DROP TABLE IF EXISTS `wpsr_zbs_tags`;
DROP TABLE IF EXISTS `wpsr_zbs_tags_links`;
DROP TABLE IF EXISTS `wpsr_zbs_tax_table`;
DROP TABLE IF EXISTS `wpsr_zbs_temphash`;
DROP TABLE IF EXISTS `wpsr_zbs_tracking`;
DROP TABLE IF EXISTS `wpsr_zbs_transactions`;
DROP TABLE IF EXISTS `wpsr_zbscrm_api_keys`;

-- ------------------------------------------------------------
-- PHASE 3: optional legacy app tables
-- Only run if the new Laravel app already replaced these modules
-- and you have validated the data you want to keep elsewhere.
-- ------------------------------------------------------------

-- DROP TABLE IF EXISTS `play_history`;
-- DROP TABLE IF EXISTS `programs`;
-- DROP TABLE IF EXISTS `songs`;
-- DROP TABLE IF EXISTS `albums`;
-- DROP TABLE IF EXISTS `videos`;
-- DROP TABLE IF EXISTS `gallery_images`;
-- DROP TABLE IF EXISTS `events`;
-- DROP TABLE IF EXISTS `theme_settings`;
-- DROP TABLE IF EXISTS `products`;
-- DROP TABLE IF EXISTS `news`;
-- DROP TABLE IF EXISTS `notifications`;
-- DROP TABLE IF EXISTS `contact_messages`;

COMMIT;

